export const providers = [
    {
        name: 'instagram',
        endpoints: [
            'https://www.instagram.com/p/*',
            'http://www.instagram.com/p/*',
            'https://instagram.com/p/*',
            'http://instagram.com/p/*',
            'http://instagr.am/p/*',
            'http://www.instagr.am/p/*',
            'https://instagr.am/p/*',
            'https://www.instagr.am/*/p/*',
            'http://instagram.com/*/p/*',
            'http://instagr.am/*/p/*',
            'http://www.instagram.com/*/p/*',
            'http://www.instagr.am/*/p/*',
            'https://instagram.com/*/p/*',
            'https://instagr.am/*/p/*',
            'https://www.instagram.com/*/p/*',
            'https://www.instagr.am/*/p/*',
            'https://www.instagr.am/p/*',
            'http://instagram.com/*/p/*,',
            'http://www.instagram.com/*/p/*,',
            'https://instagram.com/*/p/*,',
            'https://www.instagram.com/*/p/*,',
            'http://instagram.com/tv/*',
            'http://instagr.am/tv/*',
            'http://www.instagram.com/tv/*',
            'http://www.instagr.am/tv/*',
            'https://instagram.com/tv/*',
            'https://instagr.am/tv/*',
            'https://www.instagram.com/tv/*',
            'https://www.instagr.am/tv/*',
        ],
        api: 'https://graph.facebook.com/v8.0/instagram_oembed?url=',
    },
    {
        name: 'facebook',
        endpoints: [
            'https://www.facebook.com/*/posts/*',
            'https://www.facebook.com/photos/*',
            'https://www.facebook.com/*/photos/*',
            'https://www.facebook.com/photo.php*',
            'https://www.facebook.com/photo.php',
            'https://www.facebook.com/*/activity/*',
            'https://www.facebook.com/permalink.php',
            'https://www.facebook.com/media/set?set=*',
            'https://www.facebook.com/questions/*',
            'https://www.facebook.com/notes/*/*/*',
            'https://www.fb.com/*/posts/*',
            'https://www.fb.com/photos/*',
            'https://www.fb.com/*/photos/*',
            'https://www.fb.com/photo.php*',
            'https://www.fb.com/photo.php',
            'https://www.fb.com/*/activity/*',
            'https://www.fb.com/permalink.php',
            'https://www.fb.com/media/set?set=*',
            'https://www.fb.com/questions/*',
            'https://www.fb.com/notes/*/*/*',
            'http://www.facebook.com/*/posts/*',
            'http://www.facebook.com/photos/*',
            'http://www.facebook.com/*/photos/*',
            'http://www.facebook.com/photo.php*',
            'http://www.facebook.com/photo.php',
            'http://www.facebook.com/*/activity/*',
            'http://www.facebook.com/permalink.php',
            'http://www.facebook.com/media/set?set=*',
            'http://www.facebook.com/questions/*',
            'http://www.facebook.com/notes/*/*/*',
            'http://www.fb.com/*/posts/*',
            'http://www.fb.com/photos/*',
            'http://www.fb.com/*/photos/*',
            'http://www.fb.com/photo.php*',
            'http://www.fb.com/photo.php',
            'http://www.fb.com/*/activity/*',
            'http://www.fb.com/permalink.php',
            'http://www.fb.com/media/set?set=*',
            'http://www.fb.com/questions/*',
            'http://www.fb.com/notes/*/*/*',
            'https://facebook.com/*/posts/*',
            'https://facebook.com/photos/*',
            'https://facebook.com/*/photos/*',
            'https://facebook.com/photo.php*',
            'https://facebook.com/photo.php',
            'https://facebook.com/*/activity/*',
            'https://facebook.com/permalink.php',
            'https://facebook.com/media/set?set=*',
            'https://facebook.com/questions/*',
            'https://facebook.com/notes/*/*/*',
            'https://fb.com/*/posts/*',
            'https://fb.com/photos/*',
            'https://fb.com/*/photos/*',
            'https://fb.com/photo.php*',
            'https://fb.com/photo.php',
            'https://fb.com/*/activity/*',
            'https://fb.com/permalink.php',
            'https://fb.com/media/set?set=*',
            'https://fb.com/questions/*',
            'https://fb.com/notes/*/*/*',
            'http://facebook.com/*/posts/*',
            'http://facebook.com/photos/*',
            'http://facebook.com/*/photos/*',
            'http://facebook.com/photo.php*',
            'http://facebook.com/photo.php',
            'http://facebook.com/*/activity/*',
            'http://facebook.com/permalink.php',
            'http://facebook.com/media/set?set=*',
            'http://facebook.com/questions/*',
            'http://facebook.com/notes/*/*/*',
            'http://fb.com/*/posts/*',
            'http://fb.com/photos/*',
            'http://fb.com/*/photos/*',
            'http://fb.com/photo.php*',
            'http://fb.com/photo.php',
            'http://fb.com/*/activity/*',
            'http://fb.com/permalink.php',
            'http://fb.com/media/set?set=*',
            'http://fb.com/questions/*',
            'http://fb.com/notes/*/*/*',
        ],
        api: 'https://graph.facebook.com/v8.0/oembed_post?url=',
    },
    {
        name: 'facebook',
        endpoints: [
            'https://www.facebook.com/*/videos/*',
            'https://www.facebook.com/watch/*',
            'http://www.facebook.com/watch/*',
            'http://www.facebook.com/*/videos/*',
            'http://facebook.com/watch/*',
            'http://facebook.com/*/videos/*',
            'https://facebook.com/watch/*',
            'https://facebook.com/*/videos/*',
            'https://www.fb.com/watch/*',
            'https://www.fb.com/*/videos/*',
            'http://www.fb.com/watch/*',
            'http://www.fb.com/*/videos/*',
            'http://fb.com/watch/*',
            'http://fb.com/*/videos/*',
            'https://fb.com/watch/*',
            'https://fb.com/*/videos/*',

            'https://www.facebook.com/video.php?id=*',
            'https://www.facebook.com/video.php?v=*',
            'https://www.fb.com/video.php?id=*',
            'https://www.fb.com/video.php?v=*',
            'http://www.facebook.com/video.php?id=*',
            'http://www.facebook.com/video.php?v=*',
            'http://www.fb.com/video.php?id=*',
            'http://www.fb.com/video.php?v=*',
            'https://facebook.com/video.php?id=*',
            'https://facebook.com/video.php?v=*',
            'https://fb.com/video.php?id=*',
            'https://fb.com/video.php?v=*',
            'http://facebook.com/video.php?id=*',
            'http://facebook.com/video.php?v=*',
            'http://fb.com/video.php?id=*',
            'http://fb.com/video.php?v=*',
        ],
        api: 'https://graph.facebook.com/v8.0/oembed_video?url=',
    },
    {
        name: 'facebook',
        endpoints: [
            'https://www.facebook.com/*/videos/*',
            'https://www.facebook.com/watch/*',
            'http://www.facebook.com/watch/*',
            'http://www.facebook.com/*/videos/*',
            'http://facebook.com/watch/*',
            'http://facebook.com/*/videos/*',
            'https://facebook.com/watch/*',
            'https://facebook.com/*/videos/*',
            'https://www.fb.com/watch/*',
            'https://www.fb.com/*/videos/*',
            'http://www.fb.com/watch/*',
            'http://www.fb.com/*/videos/*',
            'http://fb.com/watch/*',
            'http://fb.com/*/videos/*',
            'https://fb.com/watch/*',
            'https://fb.com/*/videos/*',

            'https://www.facebook.com/*',
            'http://www.facebook.com/*',
            'https://facebook.com/*',
            'http://facebook.com/*',
            'https://www.fb.com/*',
            'http://www.fb.com/*',
            'https://fb.com/*',
            'http://fb.com/*',
        ],
        api: 'https://graph.facebook.com/v8.0/oembed_page?url=',
    },
    {
        name: 'youtube',
        endpoints: [
            'https://www.youtube.com/watch*',
            'https://youtube.com/watch*',
            'http://www.youtube.com/watch*',
            'http://youtube.com/watch*',
            'https://youtu.be/watch*',
            'http://youtu.be/watch*',
        ],
        api: 'https://www.youtube.com/oembed?url=',
    },
    {
        name: 'giphy',
        endpoints: [
            'https://giphy.com/gifs/*',
            'http://giphy.com/gifs/*',
            'https://www.giphy.com/gifs/',
            'http://www.giphy.com/gifs/',
        ],
        api: 'https://giphy.com/services/oembed?url=',
    },
    {
        name: 'reddit',
        endpoints: [
            'https://www.reddit.com/*/*/comments/*',
            'https://reddit.com/*/*/comments/*',
            'http://reddit.com/*/*/comments/*',
            'http://www.reddit.com/*/*/comments/*',
        ],
        api: 'https://www.reddit.com/oembed?url=',
    },
    {
        name: 'soundcloud',
        endpoints: [
            'https://soundcloud.com/*/*',
            'https://www.soundcloud.com/*/*',
            'http://soundcloud.com/*/*',
            'http://www.soundcloud.com/*/*',
        ],
        api: 'https://soundcloud.com/oembed?url=',
    },
    {
        name: 'vimeo',
        endpoints: [
            'https://vimeo.com/*',
            'https://vimeo.com/album/*/video/*',
            'https://vimeo.com/channels/*/*',
            'https://vimeo.com/groups/*/videos/*',
            'https://vimeo.com/ondemand/*/*',
            'https://player.vimeo.com/video/*',

            'https://www.vimeo.com/*',
            'https://www.vimeo.com/album/*/video/*',
            'https://www.vimeo.com/channels/*/*',
            'https://www.vimeo.com/groups/*/videos/*',
            'https://www.vimeo.com/ondemand/*/*',
            'https://www.player.vimeo.com/video/*',

            'http://www.vimeo.com/*',
            'http://www.vimeo.com/album/*/video/*',
            'http://www.vimeo.com/channels/*/*',
            'http://www.vimeo.com/groups/*/videos/*',
            'http://www.vimeo.com/ondemand/*/*',
            'http://www.player.vimeo.com/video/*',

            'http://vimeo.com/*',
            'http://vimeo.com/album/*/video/*',
            'http://vimeo.com/channels/*/*',
            'http://vimeo.com/groups/*/videos/*',
            'http://vimeo.com/ondemand/*/*',
            'http://player.vimeo.com/video/*',
        ],
        api: 'https://vimeo.com/api/oembed.json?url=',
    },
    {
        name: 'twitter',
        endpoints: [
            'https://twitter.com/*/status/*',

            'http://twitter.com/*/status/*',

            'https://www.twitter.com/*/status/*',

            'http://www.twitter.com/*/status/*',
        ],
        api: 'https://publish.twitter.com/oembed?url=',
    },
    {
        name: 'spotify',
        endpoints: [
            'https://open.spotify.com/track/*',
            'http://open.spotify.com/track/*',
            'http://open.spotify.com/album/*',
            'https://open.spotify.com/album/*',
            'https://open.spotify.com/playlist/*',
            'http://open.spotify.com/playlist/*',
            'https://open.spotify.com/artist/*',
            'http://open.spotify.com/artist/*',
        ],
        api: 'https://open.spotify.com/oembed?url=',
    },
];
